Repository simonsobs/LAT_MFLike, pull requests merged in 2024-02, with the labels that each got.

#71 TE/ET fix
  mflike/mflike.py
  mflike/theoryforge.py
Labels: bug

#73 Add pyproject
  .github/workflows/testing.yml
  .github/workflows/wheels.yml
  .gitignore
  MANIFEST.in
  README.rst
  binder/requirements.txt
  mflike/__init__.py
  mflike/_version.py
  mflike/mflike.py
  pyproject.toml
  setup.cfg
  setup.py
  versioneer.py
Labels: enhancement

#74 Add resources for documentation
  .github/workflows/notebooks.yml
  .github/workflows/testing.yml
  .readthedocs.yml
  README.rst
  binder/requirements.txt
  docs/Makefile
  docs/requirements.txt
  docs/source/_static/css/custom.css
  docs/source/_static/logo.png
  docs/source/conf.py
  docs/source/index.rst
  docs/source/mflike.rst
  docs/source/notebooks/Makefile
  docs/source/notebooks/tutorial_fisher.ipynb
  docs/source/notebooks/tutorial_foregrounds.ipynb
  docs/source/notebooks/tutorial_loading.ipynb
  docs/source/notebooks/tutorial_logp_value.ipynb
  docs/source/notebooks/tutorial_residuals.ipynb
  docs/source/theoryforge.rst
  mflike/__init__.py
  mflike/mflike.py
  mflike/theoryforge.py
  notebooks/mflike_tutorial.ipynb
  pyproject.toml
Labels: enhancement, documentation
